use ~/.config/nushell/nu_scripts/custom-completions/cargo/cargo-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/cargo-loco/cargo-loco-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/cargo-make/cargo-make-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/curl/curl-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/docker/docker-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/dotnet/dotnet-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/flutter/flutter-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/fsharpc/fsharpc-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/fsharpi/fsharpi-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/git/git-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/less/less-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/make/make-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/man/man-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/npm/npm-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/pnpm/pnpm-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/rustup/rustup-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/ssh/ssh-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/tar/tar-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/vscode/vscode-completions.nu *
use ~/.config/nushell/nu_scripts/custom-completions/yarn/yarn-v4-completions.nu *
