"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✖](bold red)"

[package]
disabled = true

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[[battery.display]]
threshold = 30
style = "bold red"

[cmd_duration]
min_time = 10_000
format = " took [$duration]($style)"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

# JJ status for PowerShell
[custom.jj]
description = "The current jj status"
when = "jj root"
symbol = "🥋 "
format = "[$symbol$output]($style) "
style = "bold purple"
command = "jj log -r '@' -T 'change_id.short() ++ \" \" ++ description.first_line()' --no-graph --color=always --limit 1"

# Disable all Git modules - we'll use custom ones
[git_branch]
disabled = true

[git_commit]
disabled = true

[git_status]
disabled = true

[git_metrics]
disabled = true

# Custom Git branch - only show if NOT in a jj repo
[custom.git_branch]
when = 'pwsh -NoProfile -NonInteractive -Command "if (!(Test-Path .jj)) { exit 0 } else { exit 1 }"'
command = 'git rev-parse --abbrev-ref HEAD'
description = "Only show git_branch if we're not in a jj repo"
format = "[$symbol$output]($style) "
symbol = "🌱 "
style = "bold yellow"

# Custom Git commit - only show if NOT in a jj repo
[custom.git_commit]
when = 'pwsh -NoProfile -NonInteractive -Command "if (!(Test-Path .jj)) { exit 0 } else { exit 1 }"'
command = 'git rev-parse --short HEAD'
format = "[\\($output\\)]($style) "
style = "bold yellow"
description = "Only show git_commit if we're not in a jj repo"

# Custom Git status - only show if NOT in a jj repo
[custom.git_status]
when = 'pwsh -NoProfile -NonInteractive -Command "if (!(Test-Path .jj)) { exit 0 } else { exit 1 }"'
command = 'git status --porcelain'
format = "[[$output](bold green)]($style) "
style = "bold red"
description = "Only show git_status if we're not in a jj repo"

[hostname]
ssh_only = true
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[username]
style_user = "bold dimmed blue"
show_always = false

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

[time]
time_format = "%T"
format = "🕙 $time($style) "
style = "bright-white"
disabled = false

[julia]
format = "[$symbol$version]($style) "
symbol = "ஃ "
style = "bold green"

[python]
format = "[$symbol$version]($style) "
style = "bold green"

[rust]
format = "[$symbol$version]($style) "
style = "bold green"

[nodejs]
format = "via [🤖 $version](bold green) "

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
