# yaml-language-server: $schema=https://agentgateway.dev/schema/config
config:
  database:
    url: sqlite:///Users/atrigueros/.config/agentgateway/data.db
  modelCatalog:
    - file: /Users/atrigueros/.config/agentgateway/base-costs.json
gateways:
  default:
    port: 4000
ui:
  gateways: default
llm:
  gateways: default
  models:
  - name: '*'
    provider:
      custom:
        formats:
        - type: completions
    params:
      baseUrl: https://api.z.ai/api/coding/paas/v4
      apiKey: $ZAI_API_KEY
  virtualModels: []
frontendPolicies:
  http:
    maxBufferSize: 33554432
mcp:
  gateways: default
  targets:
  - name: context7
    stdio:
      cmd: context7-mcp
      env: {}
      clear_env: false
  - name: deepwiki
    mcp:
      host: https://mcp.deepwiki.com/mcp
  - name: obsidian-brain
    stdio:
      cmd: obsidian-brain
      args:
      - server
      env: {}
      clear_env: false
  - name: z.ai-web-search-sse
    mcp:
      host: https://api.z.ai/api/mcp/web_search/sse
    policies:
      backendAuth:
        key:
          value: $ZAI_API_KEY
          location:
            queryParameter:
              name: Authorization
  port: null
  statefulMode: stateful
  prefixMode: always
  failureMode: failOpen
