[settings]
experimental = true

[daemons_settings]
namespace = "autostart-services"

[daemons.bifrost]
run = "sh -c 'export OP_SERVICE_ACCOUNT_TOKEN=$(fnox get OP_SERVICE_ACCOUNT_TOKEN) && fnox exec -- sh -c \"export ZAI_MCP_URL=https://api.z.ai/api/mcp/web_search/sse?Authorization=\\$ZAI_API_KEY && exec bifrost -port 16000\"'"
ready_port = 16000
boot_start = true

# [daemons.agentgateway]
# run = "sh -c 'export OP_SERVICE_ACCOUNT_TOKEN=$(fnox get OP_SERVICE_ACCOUNT_TOKEN) && fnox exec -- agentgateway -f $HOME/.config/agentgateway/config.yaml'"
# ready_port = 16000
# boot_start = true
